name: YouTube Stats Automation

on:
  schedule:
    - cron: "0 12 * * *"  # Runs daily at 12:00 PM UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Run YouTube Stats Script
        run: python you_stats.py
      - name: Commit CSV to GitHub
        run: |
           git config --global user.email "github-actions@github.com"
           git config --global user.name "GitHub Actions"
           git add youtube_stats.csv
    
           git diff --staged --quiet || (git commit -m "Updated YouTube stats" && git push)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

